// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <RcppEnsmallen.h>
#include <RcppThread.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pca_imp_internal_cpp
Rcpp::List pca_imp_internal_cpp(const arma::mat& obj, const arma::uvec& eligible_idx, const arma::uword ncp, const bool scale, const bool regularized, const double threshold, const arma::uword init, const arma::uword maxiter, const arma::uword miniter, arma::rowvec row_w, const double coeff_ridge);
RcppExport SEXP _slideimp_pca_imp_internal_cpp(SEXP objSEXP, SEXP eligible_idxSEXP, SEXP ncpSEXP, SEXP scaleSEXP, SEXP regularizedSEXP, SEXP thresholdSEXP, SEXP initSEXP, SEXP maxiterSEXP, SEXP miniterSEXP, SEXP row_wSEXP, SEXP coeff_ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type obj(objSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type eligible_idx(eligible_idxSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type ncp(ncpSEXP);
    Rcpp::traits::input_parameter< const bool >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< const bool >::type regularized(regularizedSEXP);
    Rcpp::traits::input_parameter< const double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type init(initSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type miniter(miniterSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type row_w(row_wSEXP);
    Rcpp::traits::input_parameter< const double >::type coeff_ridge(coeff_ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(pca_imp_internal_cpp(obj, eligible_idx, ncp, scale, regularized, threshold, init, maxiter, miniter, row_w, coeff_ridge));
    return rcpp_result_gen;
END_RCPP
}
// find_windows
List find_windows(const NumericVector x, double window, double overlap);
RcppExport SEXP _slideimp_find_windows(SEXP xSEXP, SEXP windowSEXP, SEXP overlapSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type window(windowSEXP);
    Rcpp::traits::input_parameter< double >::type overlap(overlapSEXP);
    rcpp_result_gen = Rcpp::wrap(find_windows(x, window, overlap));
    return rcpp_result_gen;
END_RCPP
}
// find_windows_flank
List find_windows_flank(NumericVector location, IntegerVector subset, double window_size);
RcppExport SEXP _slideimp_find_windows_flank(SEXP locationSEXP, SEXP subsetSEXP, SEXP window_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type location(locationSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type subset(subsetSEXP);
    Rcpp::traits::input_parameter< double >::type window_size(window_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(find_windows_flank(location, subset, window_size));
    return rcpp_result_gen;
END_RCPP
}
// impute_knn_brute
arma::mat impute_knn_brute(const arma::mat& obj, const arma::uword k, const arma::uvec& grp_impute, const arma::uvec& grp_miss_no_imp, const arma::uvec& grp_complete, const int method, const double dist_pow, int cores);
RcppExport SEXP _slideimp_impute_knn_brute(SEXP objSEXP, SEXP kSEXP, SEXP grp_imputeSEXP, SEXP grp_miss_no_impSEXP, SEXP grp_completeSEXP, SEXP methodSEXP, SEXP dist_powSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type obj(objSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type k(kSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type grp_impute(grp_imputeSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type grp_miss_no_imp(grp_miss_no_impSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type grp_complete(grp_completeSEXP);
    Rcpp::traits::input_parameter< const int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const double >::type dist_pow(dist_powSEXP);
    Rcpp::traits::input_parameter< int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(impute_knn_brute(obj, k, grp_impute, grp_miss_no_imp, grp_complete, method, dist_pow, cores));
    return rcpp_result_gen;
END_RCPP
}
// impute_knn_mlpack
arma::mat impute_knn_mlpack(const arma::mat& obj, const arma::uword k, const arma::uvec& grp_impute, const arma::uvec& grp_miss_no_imp, const arma::uvec& grp_complete, const int method, const double dist_pow, const int cores);
RcppExport SEXP _slideimp_impute_knn_mlpack(SEXP objSEXP, SEXP kSEXP, SEXP grp_imputeSEXP, SEXP grp_miss_no_impSEXP, SEXP grp_completeSEXP, SEXP methodSEXP, SEXP dist_powSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type obj(objSEXP);
    Rcpp::traits::input_parameter< const arma::uword >::type k(kSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type grp_impute(grp_imputeSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type grp_miss_no_imp(grp_miss_no_impSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type grp_complete(grp_completeSEXP);
    Rcpp::traits::input_parameter< const int >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const double >::type dist_pow(dist_powSEXP);
    Rcpp::traits::input_parameter< const int >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(impute_knn_mlpack(obj, k, grp_impute, grp_miss_no_imp, grp_complete, method, dist_pow, cores));
    return rcpp_result_gen;
END_RCPP
}
// col_min_max
arma::mat col_min_max(const arma::mat& mat);
RcppExport SEXP _slideimp_col_min_max(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(col_min_max(mat));
    return rcpp_result_gen;
END_RCPP
}
// col_vars_internal
arma::rowvec col_vars_internal(const arma::mat& mat, arma::uword cores);
RcppExport SEXP _slideimp_col_vars_internal(SEXP matSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(col_vars_internal(mat, cores));
    return rcpp_result_gen;
END_RCPP
}
// mean_imp_col_internal
arma::mat mean_imp_col_internal(const arma::mat& mat, const arma::uvec& col_idx, arma::uword cores);
RcppExport SEXP _slideimp_mean_imp_col_internal(SEXP matSEXP, SEXP col_idxSEXP, SEXP coresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type col_idx(col_idxSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type cores(coresSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_imp_col_internal(mat, col_idx, cores));
    return rcpp_result_gen;
END_RCPP
}
// check_finite
void check_finite(const arma::mat& mat);
RcppExport SEXP _slideimp_check_finite(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    check_finite(mat);
    return R_NilValue;
END_RCPP
}
// col_miss_internal
arma::uvec col_miss_internal(const arma::mat& obj);
RcppExport SEXP _slideimp_col_miss_internal(SEXP objSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type obj(objSEXP);
    rcpp_result_gen = Rcpp::wrap(col_miss_internal(obj));
    return rcpp_result_gen;
END_RCPP
}
// row_miss_internal
arma::uvec row_miss_internal(const arma::mat& obj);
RcppExport SEXP _slideimp_row_miss_internal(SEXP objSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type obj(objSEXP);
    rcpp_result_gen = Rcpp::wrap(row_miss_internal(obj));
    return rcpp_result_gen;
END_RCPP
}
// has_openmp
bool has_openmp();
RcppExport SEXP _slideimp_has_openmp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(has_openmp());
    return rcpp_result_gen;
END_RCPP
}
// sample_each_rep_cpp
arma::umat sample_each_rep_cpp(const arma::mat& obj, const arma::uvec& pool_idx_in, const arma::uvec& na_per_col, const arma::uvec& row_room, const arma::uvec& col_room, arma::uword max_attempts);
RcppExport SEXP _slideimp_sample_each_rep_cpp(SEXP objSEXP, SEXP pool_idx_inSEXP, SEXP na_per_colSEXP, SEXP row_roomSEXP, SEXP col_roomSEXP, SEXP max_attemptsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type obj(objSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type pool_idx_in(pool_idx_inSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type na_per_col(na_per_colSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type row_room(row_roomSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type col_room(col_roomSEXP);
    Rcpp::traits::input_parameter< arma::uword >::type max_attempts(max_attemptsSEXP);
    rcpp_result_gen = Rcpp::wrap(sample_each_rep_cpp(obj, pool_idx_in, na_per_col, row_room, col_room, max_attempts));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_slideimp_pca_imp_internal_cpp", (DL_FUNC) &_slideimp_pca_imp_internal_cpp, 11},
    {"_slideimp_find_windows", (DL_FUNC) &_slideimp_find_windows, 3},
    {"_slideimp_find_windows_flank", (DL_FUNC) &_slideimp_find_windows_flank, 3},
    {"_slideimp_impute_knn_brute", (DL_FUNC) &_slideimp_impute_knn_brute, 8},
    {"_slideimp_impute_knn_mlpack", (DL_FUNC) &_slideimp_impute_knn_mlpack, 8},
    {"_slideimp_col_min_max", (DL_FUNC) &_slideimp_col_min_max, 1},
    {"_slideimp_col_vars_internal", (DL_FUNC) &_slideimp_col_vars_internal, 2},
    {"_slideimp_mean_imp_col_internal", (DL_FUNC) &_slideimp_mean_imp_col_internal, 3},
    {"_slideimp_check_finite", (DL_FUNC) &_slideimp_check_finite, 1},
    {"_slideimp_col_miss_internal", (DL_FUNC) &_slideimp_col_miss_internal, 1},
    {"_slideimp_row_miss_internal", (DL_FUNC) &_slideimp_row_miss_internal, 1},
    {"_slideimp_has_openmp", (DL_FUNC) &_slideimp_has_openmp, 0},
    {"_slideimp_sample_each_rep_cpp", (DL_FUNC) &_slideimp_sample_each_rep_cpp, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_slideimp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
