# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pca_imp_internal_cpp <- function(obj, eligible_idx, ncp, scale, regularized, threshold, init, maxiter, miniter, row_w, coeff_ridge, solver, warmup_iters, lobpcg_tol, lobpcg_maxiter, trace_iter = 0L) {
    .Call(`_slideimp_pca_imp_internal_cpp`, obj, eligible_idx, ncp, scale, regularized, threshold, init, maxiter, miniter, row_w, coeff_ridge, solver, warmup_iters, lobpcg_tol, lobpcg_maxiter, trace_iter)
}

find_windows <- function(x, window, overlap = 0.0) {
    .Call(`_slideimp_find_windows`, x, window, overlap)
}

find_windows_flank <- function(location, subset, window_size) {
    .Call(`_slideimp_find_windows_flank`, location, subset, window_size)
}

impute_knn_brute <- function(obj, k, grp_impute, grp_miss_no_imp, grp_complete, method, dist_pow, cores = 1L, pb = FALSE) {
    .Call(`_slideimp_impute_knn_brute`, obj, k, grp_impute, grp_miss_no_imp, grp_complete, method, dist_pow, cores, pb)
}

impute_knn_mlpack <- function(obj, k, grp_impute, grp_miss_no_imp, grp_complete, method, dist_pow, cores = 1L) {
    .Call(`_slideimp_impute_knn_mlpack`, obj, k, grp_impute, grp_miss_no_imp, grp_complete, method, dist_pow, cores)
}

col_min_max <- function(mat) {
    .Call(`_slideimp_col_min_max`, mat)
}

col_vars_internal <- function(mat, cores = 1L) {
    .Call(`_slideimp_col_vars_internal`, mat, cores)
}

mean_imp_col_internal <- function(mat, col_idx, cores = 1L) {
    .Call(`_slideimp_mean_imp_col_internal`, mat, col_idx, cores)
}

check_finite <- function(mat) {
    invisible(.Call(`_slideimp_check_finite`, mat))
}

col_miss_internal <- function(obj) {
    .Call(`_slideimp_col_miss_internal`, obj)
}

row_miss_internal <- function(obj) {
    .Call(`_slideimp_row_miss_internal`, obj)
}

sample_each_rep_cpp <- function(obj, pool_idx_in, na_per_col, row_room, col_room, max_attempts) {
    .Call(`_slideimp_sample_each_rep_cpp`, obj, pool_idx_in, na_per_col, row_room, col_room, max_attempts)
}

